ALTER TABLE USER_ORDER
ADD COLUMN email VARCHAR(100);


ALTER TABLE ORDER_PRODUCT_MAP
ADD COLUMN name VARCHAR(255);

ALTER TABLE ORDER_PRODUCT_MAP
ADD COLUMN price BIGINT;

ALTER TABLE ORDER_PRODUCT_MAP
ADD COLUMN quantity DECIMAL;

ALTER TABLE ORDER_PRODUCT_MAP
ADD COLUMN image_url TEXT;