ALTER TABLE USER_ORDER
    ALTER COLUMN shipping_address DROP NOT NULL;

ALTER TABLE USER_ORDER
    ALTER COLUMN bill_address DROP NOT NULL;


UPDATE USER_ORDER
SET shipping_address = null;

UPDATE USER_ORDER
SET bill_address = null;

ALTER TABLE USER_ORDER
    ALTER COLUMN shipping_address TYPE BIGINT USING shipping_address::BIGINT;

ALTER TABLE USER_ORDER
    ALTER COLUMN bill_address TYPE BIGINT USING bill_address::BIGINT;

