name: Build and deploy Dockerized app to Azure Web App - financial-transaction-service

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Build with SBT
        run: sbt clean assembly

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DE0CF90E6A7340FF921963B9377C47E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DAED4AA17E8B472AA9D7AFBA0F0634EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_833A659BD31043F4942B99BFE1EB4F0D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'financial-transaction-service'
          slot-name: 'Production'
          images: 'financial-transaction-service'
